User Can See Branding and Navigation
youngmlee/sway-finance pull request #2
Opened 2017-09-01 21:26 UTC by youngmlee

Adds branding and navigation to index.html.

2017-09-01 21:37 UTC, victormejia requested changes

2017-09-01 21:37 UTC, victormejia commented on index.html
> +    <img class="branding" src="images/user-can-see-branding-and-navigation.png" alt="Picture of logo and navigation options on top of webpage" />
you can't just put the picture here. You have to re-create it using HTML and CSS.

2017-09-01 21:38 UTC, youngmlee commented
Right sorry haha

On Fri, Sep 1, 2017 at 2:37 PM, Victor Mejia <notifications@github.com>
wrote:

> *@victormejia* requested changes on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/youngmlee/sway-finance/pull/2#discussion_r136669741>:
>
> > @@ -0,0 +1,11 @@
> +<!DOCTYPE html>
> +<html lang="en-us">
> +  <head>
> +    <meta charset="utf-8" />
> +    <title>Sway Finance</title>
> +    <link href="styles.css" rel="stylesheet" />
> +  </head>
> +  <body>
> +    <img class="branding" src="images/user-can-see-branding-and-navigation.png" alt="Picture of logo and navigation options on top of webpage" />
>
> you can't just put the picture here. You have to re-create it using HTML
> and CSS.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/youngmlee/sway-finance/pull/2#pullrequestreview-60247334>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AT8jJNMPxVBsEt0-kiq2tYHZXqiUQ-xEks5seHkCgaJpZM4PKphI>
> .
>

2017-09-02 05:30 UTC, merged

2017-09-02 05:33 UTC, youngmlee commented
Screenshot of progress:
![screen shot 2017-09-01 at 10 31 41 pm](https://user-images.githubusercontent.com/20914980/29993215-929cb196-8f65-11e7-9389-b5d2589436da.png)

2017-09-04 16:38 UTC, victormejia commented
Please fix the fonts on the navigation buttons in your next pull request.